### ISSUE TITLE
return after raise

### ISSUE THREAD

**Issue by rwxd** [monkeprogramming/Minecraft-Server-Playtime#4]
The raise **or** return is wrong.

https://github.com/monkeprogramming/Minecraft-Server-Playtime/blob/c31fbf08207cffb35fd34886e171a9b91775f1b2/playtime/playtime.py#L32

**Comment by monkeprogramming** [comment]
Ja kacke, müssen wir uns wohl zusammen angucken

**Comment by rwxd** [comment]
ping
